[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 5000
maxMessageSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[client]
toolbarMode = "minimal"

[logger]
level = "info"

[theme]
base = "dark"
